# Инструкция

Это исходный файл с задачками для самостоятельной практики.<br>
Чуть позже я создам контест, с помощью которого можно будет проверить, что ваши решения выдают правильные файлы :)

**В этом ноутбуке ничего не пишем, копируем его куда удобно и немного переименовываем.** Git не будет следить на вашей копией, так что в копии можно спокойно работать. Скопированный файл может быть в этой же папке, это не проблема.

# NB !
**На контесте мы ничего не принимаем через `input`, а всё читаетм из файла `input.txt`!**
**Так что первая строка, которую вводит пользователь (задачи 1 и 2), тоже находится в файле `input.txt`.**

### Задачка 1
Дан файл `menu.csv` с информацией о позициях в кафе.<br>
Сначала принимаем от пользователя на одной строке через запятую имя позиции, которую он хочет заказать, и количество штук.<br>
Далее программа печатает, сколько ккал содержит заказ.<br>

Пользователь заказывает только одну позицию, но может заказать её сколько угодно штук.

### Задачка 2
Дан файл `menu.csv` с информацией о позициях в кафе.<br>
Сначала принимаем от пользователя на одной строке через запятую имя позиции, которую он хочет заказать, и количество штук.<br>
Далее программа печатает, сколько денег нужно заплатить, добавляя знак доллара перед числом.<br>

Пользователь заказывает только одну позицию, но может заказать её сколько угодно штук.

### Задачка 3
Дан файл с оценками `grades.csv`. Необходимо посчитать итоговые оценки всех учеников и сохранить их в csv-файл со знаком табуляции в качестве разделителя. Колонки: "Last name", "First name", "SSN", "Mark". Правила выставления оценок:  
- **A**, если среднее за все 5 тестов 90 баллов и более;
- **B**, если кол-во баллов от 75 и выше;
- **С**, если баллов >= 60;
- **D**, если от 50;
- **F** иначе.

### Задачка 4
Дан файл с текстом поэмы А.С.Пушкина "Руслан и Людмила" (`/data/ruslan_i_lyudmila.txt`).<br>Определите:<br>

#### 4.1
- число строк в файле;

#### 4.2
- суммарное число знаков препинания (будем считать знаками препинания "`.,!?:;`") (может помочь метод строк `count`);

#### 4.3
- сколько раз в поэме упоминаются слова "Руслан" и "Людмила".

**Пояснение:** необходимо посчитать вхождения слов "Руслан" и "Людмила" в именительном падеже. Слова должны начинать с большой буквы, остальные -- строчные. Если после слова или перед словом стоит какой-то знак, то это слово нужно считать (например "Руслан." или "Людмила," должны учитываться).<br>
Список знаков, которые мы игнорирует, взять из задания 4.2 (то есть наличие этого знака вплотную у слова мы игнорируем и учитываем слово при подсчете).

### Задача 5

Дан файл с помесячной информацией о числе солнечных часов для различных городов США (`data/weather_stats/sunshine.csv`).<br>
Определите город с наибольшим числом солнечных часов в феврале.<br>

PS: ваше решение должно читать файл с данными, некоторым образом его процессировать, определять нужное значение и выводить его на экран. Нужно определить только город. Искать город с максимальным чисом солнечных часов в феврале глазами или с помощью excel нельзя (думаю, это очевидно).

#### Задача 6
Дан файл с помесячной информацией о числе солнечных часов для различных городов США (`data/weather_stats/sunshine.csv`).<br>

#### 6.1
Научитесь для строки, сохраненной в переменную ниже, считать среднее число солнечных часов.

In [1]:
sunshine_row = "ABILENE, TX;62;64;70;72;70;78;80;78;71;72;67;62"
# ваш код

#### 6.2
В результирующий файл `mean_sunshine.tsv` запишите среднемесячное число солнечных часов для каждого города (в результирующем файле должно быть 2 колонки: название города+штат и среднее число sunshine).<br>
* В качестве разделителя в результирующем файле использовать знак табуляции;<br>
* Заголовок записывать не надо;<br>
* Порядок городов должен быть таким же, как в исходном файле;<br>
* Сделать "длину" первого столбца равной 30 символам, пробелы добавлять справа;<br>
* Сделать "длину" столбца со средним числом солнечных часов в 6 символов, пробелы добавлять слева, округлить до 1 знака после запятой.

### Задача 7
Дан файл с среднемесячной температурой для различных городов США (`data/weather_stats/temperature.csv`).<br>

#### 7.1
Научитесь для строки, сохраненной в переменную ниже, считать максимальную температуру.<br>
Обратите внимание, что здесь даны дробные числа, но в качестве разделителя используется запятая.<br>
`float` не умеет конвертировать строки вида "2,5" в число. Ему нужно точка в качестве разделителя.<br>
Для получения валидной страки воспользуйтесь методами строк.

In [2]:
temperature_row = "AKRON, OH;25,2;28,3;37,7;48,1;58,8;67,5;71,8;70,3;63;51,6;41,1;30,7"
# ваш код

#### 7.2
В результирующий файл `max_temp.tsv` запишите максимальую температуру для каждого города (в результирующем файле должно быть 2 колонки: название города+штат и максимальная температура).<br>
* В качестве разделителя в результирующем файле использовать знак табуляции;
* Заголовок записывать не надо;
* Порядок городов должен быть таким же, как в исходном файле;
* Сделать "длину" первого столбца равной 30 символам, пробелы добавлять **вправо**,то есть выровнять влево;
* Сделать "длину" столбца с максимальной температурой равной 3 символам, пробелы добавлять **вправо**, округлить до **меньшего целого числа**.

#### 7.3
В результирующий файл `diff_temp.tsv` запишите разницу между максимальной и минимальной среднемесячными температурами за год (в результирующем файле должно быть 2 колонки: название города+штат и разница максимальной и минимальной температур).<br>
* В качестве разделителя в результирующем файле использовать знак табуляции;
* Заголовок записывать не надо;
* Порядок городов должен быть таким же, как в исходном файле;
* Сделать "длину" первого столбца равной 30 символам, пробелы добавлять **вправо**,то есть выровнять влево;
* Сделать "длину" столбца с максимальной температурой равной 5 символам, пробелы добавлять **вправо**, округлить до одного знака после запятой.

#### 7.4
Создайте файл `unique_states.txt` с уникальными названиями штатов, отсортированными в лексикографическом порядке по возрастанию (каждый город на новой строке).

Подсказки:
* Проитерируйтесь файл;
* Вычлените из строки с названием города и штата только штат;
* Сохраняйте штат, который вы встретили впервые, в список (то есть нужно как-то проверять, а встречали ли мы штат до этого);
* Отсортировать список поможет функция `sorted` или метод списков `sort` (функция `sorted` возвращает отсортирвоанную копию, а метод `sort` сортирует in place и ничего не возвращает, примеры ниже)
* Пройтись по списку с уникальными штатами и записать каждый в новый файлик.

In [3]:
# пример c sorted
letters = ['B', 'A', 'C']     # создаем исходный спиок
letters_new = sorted(letters) # сортируем
print(letters)                # печатаем исходный список
print(letters_new)            # печатаем новый отсортированный список

['B', 'A', 'C']
['A', 'B', 'C']

In [4]:
# пример c sort
letters = ['B', 'A', 'C']     # создаем исходный спиок
letters_new = letters.sort()  # сортируем. Метод НИЧЕГО не возвращает. Переменная letters_new ПУСТАЯ!!!
print(letters)                # печатаем исходный список (он отсортирован)
print(letters_new)            # метод sort вернул НИЧЕГО, поэтому в переменной НИЧЕГО (None)

['A', 'B', 'C']
None

In [5]:
# ваш код